### PR TITLE
stty option echo is breaking functionality of serial

### PR DESCRIPTION
**Pull request by Kaisrlik**

### CODE REVIEW

**Comment by wentasah** [comment]
I don't really understand what's broken. Please describe what is broken and how your change fixes that. Also, the `$stty` variable changed in your commit is only the default value and you can change it with `--stty` command line option.

If the current default turns not to be useful for anybody, I'll happily change it, but I remember myself using it successfully some years ago.

**Comment by Kaisrlik** [comment]
Ok, let me explain the problem. 

Time to time I observe that the novaboot hangs in the uboot menu with weird characters on the line like this
```
=> MC:   mmc@7000: 0^M^JLoading Environment from MMC... OK^M^JIn:    serial@3000^M^JNet:   eth0: ethernet@ff3f0000^M^JHit any key to stop autoboot:  2 ^H^H^H 0^M^J=> MC:   mmc@7000: 0^M^JLoading Environment from MMC... OK^M^JIn:    serial@3000^M^JNet:   
Unknown command 'MC:' - try 'help'
```
When I tried to play with stty option I realized that `echo` option also breaking the communication(and I do not why but It also fixes my problem). So I tested following option:
* `--stty="raw -crtscts -onlcr 115200 -echo"` (working)
* `--stty="raw -crtscts -onlcr 115200 echo"` (not working)

The reason why I'm sending the patch instead of using `--stty` option is that the default option given to stty does not modify `echo` which is breaking output of the serial. So I think it is better to set it explicitly than believe the option is set correctly.

If you do not want to merge it. Feel free to close it.

**Comment by wentasah** [comment]
I see. I'll test it on my system tomorrow and probably will merge it.

**Comment by wentasah** [comment]
I've modified the commit message and merged it. Thanks.

**Pull request closed without merging**
